on: [workflow_dispatch, push]
  
jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: version
        name: Calculate version
        uses: paulhatch/semantic-version@v5.0.0-alpha2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push pre-release
        uses: docker/build-push-action@v3
        if: ${{ steps.version.outputs.increment > 0}}
        with:
          context: src
          push: true
          tags: ghcr.io/ist-ltd/dolt:${{ steps.version.outputs.version }}-pre${{ steps.version.outputs.increment }}
        
      - name: Build and push release
        uses: docker/build-push-action@v3
        if: ${{ steps.version.outputs.increment == 0}}
        with:
          context: src
          push: true
          tags: ghcr.io/ist-ltd/dolt:${{ steps.version.outputs.version }}
          